### ISSUE TITLE
highlighting for sudo commands

### ISSUE THREAD

**Issue by oschmid** [zsh-users/zsh-syntax-highlighting#107]
zsh can complete commands that are on root's path but not on user's path by adding the following to .zshrc
```zsh
zstyle ':completion:*:sudo::' environ PATH="/sbin:/usr/sbin:$PATH" HOME="/root"
```
But these commands aren't being properly highlighted by zsh-syntax-highlighting. Instead of green (valid command) they are appearing red (invalid command). Is there a setting similar to environ to change this?

**Comment by guidovansteen** [comment]
I just checked this bug. It seems to have been fixed since it was reported. 

So let us close it.

**Comment by danielshahaf** [comment]
Can you describe the working setup? I can still reproduce it on debian with zsh-5.1 under `zsh -f``, even if I set both the `environ` and `command-path` styles. It only works for me if I add /sbin to my $PATH.

(Reopening until we figure this out.)

**Comment by guidovansteen** [comment]
Sorry for the noise. /sbin was added my $path when I tried this earlier today. Thanks for reopening!

**Comment by danielshahaf** [comment]
In 0.4..1 commands from root's path are highlighted in red.  During 0.5.0 development they were shown in default (like any not-otherwise-special word), but 757d047f09cda75a74ce62e198504893335f9ad5 (in 0.5.0-to-be) restores the behaviour of 0.4.1.

**Comment by danielshahaf** [comment]
Various ideas:

- Can we obtain the `secure_path` option from `sudoers(5)`?
- We could inspect the `environ PATH` or `command-path` completion style in the `:completion:…:sudo` context.  (Why that context?  Because that's the context the style definition's context patterns would match.  Yes, this is somewhat hacky.)
- We could take a wild guess with `${path//\/bin/\/sbin}`.

Or we could do something else entirely:
- Never highlight the `foo` in `sudo foo` as an unknown command.
