### ISSUE TITLE
Widget binding ignores are breaking hchbaw/opp.zsh

### ISSUE THREAD

**Issue by zhimsel** [zsh-users/zsh-syntax-highlighting#278]
If I use both zsh-syntax-highlighting and opp.zsh, opp produces an error whenever a new shell is started: 

```
(eval):1: bad pattern: orig-opp-gps-( opp-gps-(
(eval):1: parse error near `)'
(eval):1: parse error near `;'
(eval):1: parse error near `;'
(eval):1: bad pattern: orig-opp-gps-[
(eval):1: parse error near `}'
```

I was able to narrow it down to `zsh-syntax-highlighting`, and discovered this behavior was introduced in 18df692. The previous commit (7044c19) works fine.

My zshrc is available here: https://github.com/zhimsel/dotfiles/blob/master/zshrc
That should be current and live on my machine.

**Comment by zhimsel** [comment]
Upon further digging, it looks like specifically 487b122c480d00befc3f80a8cc2e53ad99593b2c is the culprit. If I revert that specific commit, the error is not produced.

**Comment by danielshahaf** [comment]
@m0vie It's your patch, could you have a look?

@zhimsel Could you please try to reproduce the problem in `zsh -f` followed by `source .../opp.zsh; source ../zsh-syntax-highlighting.zsh`?

**Comment by danielshahaf** [comment]
I guess we need either to get rid of the `eval`, or to use ${(q)} or ${(b)}.  (in a way that's backwards-compatible to older zsh's)

**Comment by zhimsel** [comment]
@danielshahaf:

```shell
$ zsh -f
% source opp/opp.zsh
% source zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
% 
```
Seems to work.

**Comment by zhimsel** [comment]
Correction, it does not. Sorry, I was using the wrong commit. Same error when using `master/HEAD`:

```shell
$ zsh -f
% source opp/opp.zsh
% source zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
(eval):1: bad pattern: orig-opp-gps-( opp-gps-(
(eval):1: parse error near `)'
(eval):1: parse error near `;'
(eval):1: parse error near `;'
(eval):1: bad pattern: orig-opp-gps-[
(eval):1: parse error near `}'
%
```

**Comment by danielshahaf** [comment]
@zhimsel Should be fixed in latest master; apologies for the delay.

@m0vie I'm a bit unsatisfied at having had to fix a bug introduced by a colleague; normally people should fix their own bugs.  I guess you were going to look into it over the upcoming weekend, though?

**Comment by zhimsel** [comment]
@danielshahaf upon updating master, and launching a new shell I get the following:

```shell
_zsh_highlight_bind_widgets:zle:24: not enough arguments for -C
_zsh_highlight_bind_widgets:zle:24: not enough arguments for -C
_zsh_highlight_bind_widgets:zle:24: not enough arguments for -C
<repeated a bunch>
10:23:54 zach at randir in ~/dotfiles/zsh/zsh-syntax-highlighting
$
No such widget `orig-'
```
I also cannot enter text on the prompt. Line editing is not permitted at all.

**Comment by danielshahaf** [comment]
`make test` didn't catch this :(

**Comment by danielshahaf** [comment]
Fixed the breakage.  Currently the opp.zsh has resurfaced, will fix that later.

**Comment by danielshahaf** [comment]
@zhimsel All done.

**Comment by zhimsel** [comment]
@danielshahaf Groovy. Line editing is working again. Still getting that `not enough arguments` error ~20 times before the first prompt, but I imagine that's related to the opp.zsh issue, not what you just fixed.

**Comment by danielshahaf** [comment]
Nope, it was a bug.  Should be fixed by 11d3783.

**Comment by danielshahaf** [comment]
... and cb02451a4e08.  Not my best day ☹

**Comment by zhimsel** [comment]
Ha, we've all been there. Seems to be fixed now, thanks!

**Comment by m0vie** [comment]
@danielshahaf yes, I was going to look into it this weekend. Technically the bug was always there in the widget binding, my change just coincidentally made opp.zsh a candidate to run into it.
I hadn't fully understood the way the widget eval code worked, so I didn't want to rush anything.

Thank you for taking the time to fix it!

P.S.: I still don't fully understand why the one eval is still needed.

**Comment by danielshahaf** [comment]
> @danielshahaf yes, I was going to look into it this weekend. Technically the bug was always there in the widget binding, my change just coincidentally made opp.zsh a candidate to run into it.
> I hadn't fully understood the way the widget eval code worked, so I didn't want to rush anything.
> 
> Thank you for taking the time to fix it!
> 

No problem.  I wasn't sure whether you were busy or waiting for the weekend, so I just jumped in.  No sweat.

> P.S.: I still don't fully understand why the one eval is still needed.

Because function bodies use dynamic scoping:

```zsh
% cur_widget=foo
% f_$cur_widget() { echo $cur_widget }
% cur_widget=bar
% f_foo
bar
```

The `eval` forces the parameter reference `$cur_widget` in the function body to be evaluated at function declaration time, rather than at function execution time:

```zsh
% cur_widget=foo
% eval "f_${(q)cur_widget}() { echo ${(q)cur_widget} }"
% cur_widget=bar
% f_foo
foo
```
