### ISSUE TITLE
zsh-syntax-hightling + zsh-autocorrect breaks history-incremental-pattern-search-backward

### ISSUE THREAD

**Issue by docwhat** [zsh-users/zsh-syntax-highlighting#387]
In my zsh configuration if I load both `zsh-syntax-highlighting` and `zsh-autocorrect` then `history-incremental-pattern-search-backward` is broken (I have it bound to `^R`.

If I disable one or the other, then `history-incremental-pattern-search-backward`.

If I leave `^R` bound to its default, `history-incremental-search-backward` then that works as well.

The load order of `zsh-syntax-highlighting` and `zsh-autocorrect` doesn't seem to make any difference.

I created a minimal test case for you: https://gist.github.com/docwhat/0cd192c066a5f9da69244f1631c5d481

My files:
* [all my dotfiles](https://github.com/docwhat/dotfiles) -- The zshrc files are loaded from `zsh/startup/*.zsh`.
* [my plugins being loaded](https://github.com/docwhat/dotfiles/blob/master/zsh/startup/0plugins.zsh)
* [where I do bindkeys](https://github.com/docwhat/dotfiles/blob/master/zsh/startup/edit-mode.zsh)

**Comment by danielshahaf** [comment]
> In my zsh configuration if I load both `zsh-syntax-highlighting` and `zsh-autocorrect` then `history-incremental-pattern-search-backward` is broken (I have it bound to `^R`.
> 
> If I disable one or the other, then `history-incremental-pattern-search-backward`.
> 
> If I leave `^R` bound to its default, `history-incremental-search-backward` then that works as well.
> 
> The load order of `zsh-syntax-highlighting` and `zsh-autocorrect` doesn't seem to make any difference.
> 
> I created a minimal test case for you: https://gist.github.com/docwhat/0cd192c066a5f9da69244f1631c5d481
> 

Thanks for the minimal example.  Haven't looked yet, but two quick comments:

1. This will probably fixed by #245 (the fix for which is already written, and is only waiting for zsh 5.3 to be released).

2. I wonder if the patch at https://github.com/zsh-users/zsh-autosuggestions/issues/126#issuecomment-217041261 fixes this issue as well.  (Need to run `make` after applying it to zsh-autosuggestions.)

**Comment by docwhat** [comment]
I'm looking forward to 5.3, then. :-)

The mini-patch you provided did not fix my test-case (posted above) nor my normal shell environment. :-(

**Comment by danielshahaf** [comment]
Thanks for testing the patch and for the very detailed followup.

Are you sure z-asug is involved here?  If I do just:

```zsh
% bindkey '^R' history-incremental-pattern-search-backward 
% echo foo
% echo bar
% <press Ctrl+R>echo<press Ctrl+R>
```

then the result is different if I source z-sy-h after the bindkey,
compared to if I don't source z-sy-h at all.

That's with zsh master and z-sy-h master (which still use the
5.2-and-earlier codepath), in `zsh -f`.

**Comment by danielshahaf** [comment]
... and #245 does _not_ solve this issue.

**Comment by danielshahaf** [comment]
Milestone 0.6.0 — I'd like to understand the root cause before 0.6.0.

**Comment by docwhat** [comment]
After much digging through code and reading up on what `zle` and widgets are, etc...

This fixes the problem:

``` .zsh
source ~/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/zsh-autosuggestions/zsh-autosuggestions.zsh

typeset -ar ZSH_AUTOSUGGEST_IGNORE_WIDGETS=(
  "${ZSH_AUTOSUGGEST_IGNORE_WIDGETS[@]}"
  zle-isearch-update
)
```

So it looks like whatever zsh-autosuggest is doing to `zle-isearch-update` is breaking backwards search, but only if I enabled zsh-syntax-highlighting too.

**Comment by danielshahaf** [comment]
> After much digging through code and reading up on what `zle` and widgets are, etc...

Feel free to join #zsh or #zsh-syntax-highlighting on freenode with any questions.

> This fixes the problem:
> 
> ``` .zsh
> source ~/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> source ~/zsh-autosuggestions/zsh-autosuggestions.zsh
> 
> typeset -ar ZSH_AUTOSUGGEST_IGNORE_WIDGETS=(
>   "${ZSH_AUTOSUGGEST_IGNORE_WIDGETS[@]}"
>   zle-isearch-update
> )
> ```
> 
> So it looks like whatever zsh-autosuggest is doing to `zle-isearch-update` is breaking backwards search, but only if I enabled zsh-syntax-highlighting too.

That's interesting.

This explains why the redrawhook branch is also affected: it wraps
`zle-isearch-update` in the pre-5.2 way.

Could you try whether the problem reproduces with `zle-isearch-update() { zle .zle-isearch-update  -- "$@" ; false }` and zsh-autosuggestions, but without z-sy-h?  I don't see anything obviously wrong in either codebase, but it's late here and I could easily be missing something.

Thanks for narrowing this down.

**Comment by docwhat** [comment]
> Could you try whether the problem reproduces with `zle-isearch-update() { zle .zle-isearch-update  -- "$@" ; false }` and zsh-autosuggestions, but without z-sy-h?

I took it for a spin in my test-gist and everything worked correctly. The problem didn't appear.

``` .zsh
# Lines from .zshrc:
zle-isearch-update() { zle .zle-isearch-update  -- "$@" ; false }
source ~/zsh-autosuggestions/zsh-autosuggestions.zsh
```

`zle -la | grep isearch` returned nothing, so I'm not sure the test did what you wanted.

**Comment by danielshahaf** [comment]
> > Could you try whether the problem reproduces with `zle-isearch-update() { zle .zle-isearch-update  -- "$@" ; false }` and zsh-autosuggestions, but without z-sy-h?
> 
> I took it for a spin in my test-gist and everything worked correctly. The problem didn't appear.
> 
> ``` .zsh
> # Lines from .zshrc:
> zle-isearch-update() { zle .zle-isearch-update  -- "$@" ; false }
> source ~/zsh-autosuggestions/zsh-autosuggestions.zsh
> ```
> 
> `zle -la | grep isearch` returned nothing, so I'm not sure the test did what you wanted.

Indeed it didn't, sorry about that.  What I had in mind was `zle-isearch-update() {}; zle -N zle-isearch-update`.

**Comment by docwhat** [comment]
Yup; this causes the exact same issue in zsh-autosuggest:

```
# Lines from .zshrc
zle-isearch-update() {}; zle -N zle-isearch-update
source ~/zsh-autosuggestions/zsh-autosuggestions.zsh
```

**Comment by danielshahaf** [comment]
> Yup; this causes the exact same issue in zsh-autosuggest:
> 
> ```
> # Lines from .zshrc
> zle-isearch-update() {}; zle -N zle-isearch-update
> source ~/zsh-autosuggestions/zsh-autosuggestions.zsh
> ```

In this case, I suggest you report this as a bug against zsh-autosuggestions, since you're about to reproduce the bug without zsh-syntax-highlighting.

Thanks for your help diagnosing the issue!

**Comment by docwhat** [comment]
Done!
